fix

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -62,29 +62,29 @@ jobs:
             }
 
     sonarcloud:
-    docker:
-      - image: sonarsource/sonar-scanner-cli:10
-    steps:
-      - checkout
-      - run:
-          name: Instalar jq
-          command: apk add --no-cache jq curl
-      - run:
-          name: Ejecutar análisis de SonarCloud
-          command: |
-            sonar-scanner \
-              -Dsonar.projectKey=your_project_key \
-              -Dsonar.organization=your_organization_key \
-              -Dsonar.host.url=https://sonarcloud.io \
-              -Dsonar.login=$SONAR_TOKEN
-      - run:
-          name: Comprobar Quality Gate
-          command: |
-            status=$(curl -s -u $SONAR_TOKEN: "https://sonarcloud.io/api/qualitygates/project_status?projectKey=your_project_key" | jq -r .projectStatus.status)
-            if [ "$status" != "OK" ]; then
-              echo "Quality gate failed"
-              exit 1
-            fi
+      docker:
+        - image: sonarsource/sonar-scanner-cli:10
+      steps:
+        - checkout
+        - run:
+            name: Instalar jq
+            command: apk add --no-cache jq curl
+        - run:
+            name: Ejecutar análisis de SonarCloud
+            command: |
+              sonar-scanner \
+                -Dsonar.projectKey=your_project_key \
+                -Dsonar.organization=your_organization_key \
+                -Dsonar.host.url=https://sonarcloud.io \
+                -Dsonar.login=$SONAR_TOKEN
+        - run:
+            name: Comprobar Quality Gate
+            command: |
+              status=$(curl -s -u $SONAR_TOKEN: "https://sonarcloud.io/api/qualitygates/project_status?projectKey=your_project_key" | jq -r .projectStatus.status)
+              if [ "$status" != "OK" ]; then
+                echo "Quality gate failed"
+                exit 1
+              fi
       
   pepe:
     docker:
