sonarcloud yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -60,7 +60,36 @@ jobs:
                 }
               ]
             }
-        
+
+  sonarcloud:
+    docker:
+      - image: cimg/node:18.20.3
+    steps:
+      - checkout
+      - run:
+          name: Install SonarScanner
+          command: |
+            npm install -g sonarqube-scanner
+      - run:
+          name: Run SonarCloud analysis
+          command: |
+            sonar-scanner \
+              -Dsonar.projectKey=your_project_key \
+              -Dsonar.organization=your_organization_key \
+              -Dsonar.host.url=https://sonarcloud.io \
+              -Dsonar.login=$SONAR_TOKEN
+      - run:
+          name: Check Quality Gate
+          command: |
+            status=$(curl -s -u $SONAR_TOKEN: "https://sonarcloud.io/api/qualitygates/project_status?projectKey=your_project_key" | jq -r .projectStatus.status)
+            if [ "$status" != "OK" ]; then
+              echo "Quality gate failed"
+              exit 1
+            fi
+      - slack/notify:
+          channel: general
+          event: fail
+          template: basic_fail   
      
 
   deploy:
